export const visaFreeCountries = [
  { name: 'Austria', continent: 'European', h114: true, hainan: true },
  { name: 'Belgium', continent: 'European', h114: true, hainan: true },
  { name: 'Czech Republic', continent: 'European', h114: true, hainan: true },
  { name: 'Denmark', continent: 'European', h114: true, hainan: true },
  { name: 'Estonia', continent: 'European', h114: true, hainan: true },
  { name: 'Finland', continent: 'European', h114: true, hainan: true },
  { name: 'France', continent: 'European', h114: true, hainan: true },
  { name: 'Germany', continent: 'European', h114: true, hainan: true },
  { name: 'Greece', continent: 'European', h114: true, hainan: true },
  { name: 'Hungary', continent: 'European', h114: true, hainan: true },
  { name: 'Iceland', continent: 'European', h114: true, hainan: true },
  { name: 'San Marino', continent: 'European', d30: true },
  { name: 'Italy', continent: 'European', h114: true, hainan: true },
  { name: 'Latvia', continent: 'European', h114: true, hainan: true },
  { name: 'Lithuania', continent: 'European', h114: true, hainan: true },
  { name: 'Luxembourg', continent: 'European', h114: true },
  { name: 'Malta', continent: 'European', h114: true, hainan: true },
  { name: 'Netherlands', continent: 'European', h114: true, hainan: true },
  { name: 'Poland', continent: 'European', h114: true, hainan: true },
  { name: 'Portugal', continent: 'European', h114: true, hainan: true },
  { name: 'Slovakia', continent: 'European', h114: true, hainan: true },
  { name: 'Slovenia', continent: 'European', h114: true, hainan: true },
  { name: 'Spain', continent: 'European', h114: true, hainan: true },
  { name: 'Sweden', continent: 'European', h114: true, hainan: true },
  { name: 'Switzerland', continent: 'European', h114: true, hainan: true },
  { name: 'Monaco', continent: 'European', h114: true, hainan: true },
  { name: 'Russia', continent: 'European', h114: true, hainan: true },
  { name: 'United Kingdom', continent: 'European', h114: true, hainan: true },
  { name: 'Ireland', continent: 'European', h114: true, hainan: true },
  { name: 'Cyprus', continent: 'European', h114: true, hainan: true },
  { name: 'Bulgaria', continent: 'European', h114: true, hainan: true },
  { name: 'Romania', continent: 'European', h114: true, hainan: true },
  { name: 'Ukraine', continent: 'European', h114: true, hainan: true },
  { name: 'Serbia', continent: 'European', h114: true, d30: true, hainan: true },
  { name: 'Croatia', continent: 'European', h114: true, hainan: true },
  { name: 'Bosnia and Herzegovina', continent: 'European', h114: true, d30: true, hainan: true },
  { name: 'Montenegro', continent: 'European', h114: true, hainan: true },
  { name: 'North Macedonia', continent: 'European', h114: true, hainan: true },
  { name: 'Albania', continent: 'European', h114: true, d30: true, hainan: true },
  { name: 'Belarus', continent: 'European', h114: true, d30: true, hainan: true },
  { name: 'Norway', continent: 'European', h114: true, hainan: true },
  { name: 'Mauritius', continent: 'Africa', d30: true },
  { name: 'Seychelles', continent: 'Africa', d30: true },
  { name: 'Antigua and Barbuda', continent: 'American', d30: true },
  { name: 'United States', continent: 'American', h114: true, hainan: true },
  { name: 'Grenada', continent: 'American', d30: true },
  { name: 'Ecuador', continent: 'American', d30: true },
  { name: 'Dominica', continent: 'American', d30: true },
  { name: 'Barbados', continent: 'American', d30: true },
  { name: 'Canada', continent: 'American', h114: true, hainan: true },
  { name: 'Brazil', continent: 'American', h114: true, hainan: true },
  { name: 'Mexico', continent: 'American', h114: true, hainan: true },
  { name: 'Argentina', continent: 'American', h114: true, hainan: true },
  { name: 'Chile', continent: 'American', h114: true, hainan: true },
  { name: 'The Bahamas', continent: 'American', d30: true },
  { name: 'Surinam', continent: 'American', d30: true },
  { name: 'Australia', continent: 'Oceanian', h114: true, hainan: true },
  { name: 'New Zealand', continent: 'Oceanian', h114: true, hainan: true },
  { name: 'Tonga', continent: 'Oceanian', d30: true },
  { name: 'Fiji', continent: 'Oceanian', d30: true },
  { name: 'Maldives', continent: 'Asian', d30: true },
  { name: 'Armenia', continent: 'Asian', d30: true },
  { name: 'Kazakhstan', continent: 'Asian', d30: true, hainan: true },
  { name: 'Georgia', continent: 'Asian', d30: true },
  { name: 'Thailand', continent: 'Asian', d30: true, hainan: true },
  { name: 'South Korea', continent: 'Asian', h114: true },
  { name: 'The Republic of Korea', continent: 'Asian', hainan: true },
  { name: 'The Philippines', continent: 'Asian', hainan: true },
  { name: 'Indonesia', continent: 'Asian', hainan: true },
  { name: 'Japan', continent: 'Asian', h114: true, hainan: true },
  { name: 'Singapore', continent: 'Asian', h114: true, d30: true, hainan: true },
  { name: 'Brunei', continent: 'Asian', h114: true, hainan: true },
  { name: 'United Arab Emirates', continent: 'Asian', h114: true, d30: true, hainan: true },
  { name: 'Qatar', continent: 'Asian', h114: true, d30: true, hainan: true },
];
