export const visaFreeCountries = [
  { name: 'Austria', continent: 'European' },
  { name: 'Belgium', continent: 'European' },
  { name: 'Czech Republic', continent: 'European' },
  { name: 'Denmark', continent: 'European' },
  { name: 'Estonia', continent: 'European' },
  { name: 'Finland', continent: 'European' },
  { name: 'France', continent: 'European' },
  { name: 'Germany', continent: 'European' },
  { name: 'Greece', continent: 'European' },
  { name: 'Hungary', continent: 'European' },
  { name: 'Iceland', continent: 'European' },
  { name: 'Italy', continent: 'European' },
  { name: 'Latvia', continent: 'European' },
  { name: 'Lithuania', continent: 'European' },
  { name: 'Luxembourg', continent: 'European' },
  { name: 'Malta', continent: 'European' },
  { name: 'Netherlands', continent: 'European' },
  { name: 'Poland', continent: 'European' },
  { name: 'Portugal', continent: 'European' },
  { name: 'Slovakia', continent: 'European' },
  { name: 'Slovenia', continent: 'European' },
  { name: 'Spain', continent: 'European' },
  { name: 'Sweden', continent: 'European' },
  { name: 'Switzerland', continent: 'European' },
  { name: 'Monaco', continent: 'European' },
  { name: 'Russia', continent: 'European' },
  { name: 'United Kingdom', continent: 'European' },
  { name: 'Ireland', continent: 'European' },
  { name: 'Cyprus', continent: 'European' },
  { name: 'Bulgaria', continent: 'European' },
  { name: 'Romania', continent: 'European' },
  { name: 'Ukraine', continent: 'European' },
  { name: 'Serbia', continent: 'European' },
  { name: 'Croatia', continent: 'European' },
  { name: 'Bosnia and Herzegovina', continent: 'European' },
  { name: 'Montenegro', continent: 'European' },
  { name: 'North Macedonia', continent: 'European' },
  { name: 'Albania', continent: 'European' },
  { name: 'Belarus', continent: 'European' },
  { name: 'Norway', continent: 'European' },
  { name: 'United States', continent: 'American' },
  { name: 'Canada', continent: 'American' },
  { name: 'Brazil', continent: 'American' },
  { name: 'Mexico', continent: 'American' },
  { name: 'Argentina', continent: 'American' },
  { name: 'Chile', continent: 'American' },
  { name: 'Australia', continent: 'Oceanian' },
  { name: 'New Zealand', continent: 'Oceanian' },
  { name: 'South Korea', continent: 'Asian' },
  { name: 'Japan', continent: 'Asian' },
  { name: 'Singapore', continent: 'Asian' },
  { name: 'Brunei', continent: 'Asian' },
  { name: 'United Arab Emirates', continent: 'Asian' },
  { name: 'Qatar', continent: 'Asian' },
];
